myapp/myapp/urls.py
from django.conf import settings 
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dj-admin/', admin.site.urls),
    path('', include('mysite.urls')),
] 

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/mysite/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *

urlpatterns = [
   path('admin/', admin_login, name='admin_login'),
   path('logout/', auth_views.LogoutView.as_view(), name='logout'),
   path('dashboard/', dashboard, name='dashboard'),
   path('product/', product_list, name='product_list'),
   path('update_product/<int:product_id>/', update_product, name='update_product'),
   path('delete_product/<int:product_id>/', delete_product, name='delete_product'),
   path('add_product/', add_product, name='add_product'),
]

myapp/mysite/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=50)
    email = models.EmailField()
    password = models.CharField(max_length=100)


    def __str__(self):
        return self.username

class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    
    def __str__(self):
        return self.name

myapp/mysite/forms.py
# forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price']

myapp/mysite/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import ProductForm

def admin_login(request):
    try:
        if request.user.is_authenticated:
            return redirect('/dashboard')

        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
          
            user_obj = authenticate(request, username=username, password=password)

            if user_obj and user_obj.is_superuser:
                login(request, user_obj)
                return redirect('/dashboard/')
            else:
                messages.error(request, 'Invalid username or password')

        return render(request, 'login.html')

    except Exception as e:
        print(e)


def product_list(request): 
    products = Product.objects.all()
    return render(request, 'product.html', {'products': products})


def update_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = ProductForm(instance=product)

    return render(request, 'dashboard.html', {'form': form, 'product': product})

def delete_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'DELETE':
        product.delete()
        return JsonResponse({'success': True})
    else:
        return JsonResponse({'success': False})
    
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return JsonResponse({'success': True})
        else:
            return JsonResponse({'success': False, 'errors': form.errors})
    else:
        form = ProductForm()

    return render(request, 'add_product.html', {'form': form})

def dashboard(request):
    return render(request, 'dashboard.html')

myapp/mysite/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

    <!-- Include Materialize CSS/JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>

    <nav>
        <div class="nav-wrapper">
            <a class="right" href="{% url 'logout' %}">Logout</a>
            <ul id="nav-mobile" class="left hide-on-med-and-down">
                <li><a href="{% url 'product_list' %}">Products</a></li>
                <li><a href="">Users</a></li>
            </ul>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

</body>


</html>

myapp/mysite/templates/head/css.html
{% load static %}
<link rel="stylesheet" href="{% static 'custom/custom.css' %}">
<link rel="stylesheet" href="{% static 'css/mysite-ui.css' %}">

myapp/mysite/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% include 'head/css.html' %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
</head>

<body>

   <div class="container p-8">
    <form method="post">
        <!-- Email input -->
        <div class="form-outline mb-4">
          <input type="email" id="form2Example1" name="username" class="form-control" />
          <label class="form-label" for="form2Example1">Username</label>
        </div>
      
        <!-- Password input -->
        <div class="form-outline mb-4">
          <input type="password" id="form2Example2" name="password" class="form-control" />
          <label class="form-label" for="form2Example2">Password</label>
        </div>
      
        <!-- 2 column grid layout for inline styling -->
        <div class="row mb-4">
          <div class="col d-flex justify-content-center">
            <!-- Checkbox -->
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="form2Example31" checked />
              <label class="form-check-label" for="form2Example31"> Remember me </label>
            </div>
          </div>
      
          <div class="col">
            <!-- Simple link -->
            <a href="#!">Forgot password?</a>
          </div>
        </div>
      
        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>
      
        <!-- Register buttons -->
        <div class="text-center">
          <p>Not a member? <a href="#!">Register</a></p>
          <p>or sign up with:</p>
          <button type="button" class="btn btn-link btn-floating mx-1">
            <i class="fab fa-facebook-f"></i>
          </button>
      
          <button type="button" class="btn btn-link btn-floating mx-1">
            <i class="fab fa-google"></i>
          </button>
      
          <button type="button" class="btn btn-link btn-floating mx-1">
            <i class="fab fa-twitter"></i>
          </button>
      
          <button type="button" class="btn btn-link btn-floating mx-1">
            <i class="fab fa-github"></i>
          </button>
        </div>
      </form>
   </div>
</body>

</html>

myapp/mysite/templates/product.html
{% extends 'dashboard.html' %}
{% block content %}
<div class="container p-8">
    <a class="waves-effect waves-light btn modal-trigger" href="#addProductModal">
        <i class="material-icons left">add</i>Add Product
    </a>
    
    <div id="addProductModal" class="modal">
        <div class="modal-content">
      
            <form id="addProductForm" method="post" action="{% url 'add_product' %}">
                {% csrf_token %}
                <label for="new_name">Name</label>
                <input id="new_name" name="name" type="text" class="validate">
    
                <label for="new_price">Price</label>
                <input id="new_price" name="price" type="text" class="validate">
            </form>
        </div>
        <div class="modal-footer">
            <a href="#" onclick="addProduct()" class="waves-effect waves-green btn-flat">Add</a>
        </div>
    </div>
    <table class="responsive-table">
        <thead>
            <tr>
                <th>Stt</th>
                <th>Name</th>
                <th>Price</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            {% for p in products %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ p.name }}</td>
                <td>{{ p.price }}</td>
                <td>
                    <a class="waves-effect waves-light btn modal-trigger" href="#modal{{ forloop.counter }}"><i
                            class="material-icons">create</i></a>

                    <!-- Your modal -->
                    <div id="modal{{ forloop.counter }}" class="modal">
                        <form id="updateForm{{ forloop.counter }}" method="post"
                            action="{% url 'update_product' p.id %}">
                            {% csrf_token %}
                            <div class="modal-content">
                                <label for="id_name">Name</label>
                                <input id="id_name" name="name" type="text" class="validate" value="{{ p.name }}">

                                <label for="id_price">Price</label>
                                <input id="id_price" name="price" type="text" class="validate"
                                    value="{{ p.price }}">
                            </div>
                            <div class="modal-footer">
                                <button type="button" onclick="updateProduct('{{forloop.counter}}')"
                                    class="waves-effect waves-green btn-flat">Update</button>
                            </div>
                        </form>
                    </div>


                    <a class="waves-effect waves-light btn red modal-trigger"
                        href="#deleteModal{{ forloop.counter }}">
                        <i class="material-icons">delete</i>
                    </a>

                    <!-- Delete Modal -->
                    <div id="deleteModal{{ forloop.counter }}" class="modal">
                        <div class="modal-content">
                            <h4>Delete Product</h4>
                            <p>Are you sure you want to delete this product?</p>
                        </div>
                        <div class="modal-footer">
                            <a href="#!" class="modal-close waves-effect waves-green btn-flat">Cancel</a>
                            <a href="#" onclick="deleteProduct('{{forloop.counter}}')"
                                class="waves-effect waves-red btn-flat">Delete</a>
                        </div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    $(document).ready(function () {
        $('.modal').modal();
    });

    function updateProduct(productId) {
        var form = document.getElementById('updateForm' + productId);
        var formData = new FormData(form);

        fetch(form.action, {
            method: 'POST',
            body: formData,
            headers: {
                'X-CSRFToken': document.getElementsByName('csrfmiddlewaretoken')[0].value,
            },
        })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                    Swal.fire({
                        icon: 'success',
                        title: 'Update Successful',
                        showConfirmButton: true,
                    })
                        .then((result) => {
                            if (result.isConfirmed || result.isDismissed) {
                                location.reload();
                            }
                        });
                } else {
                    // Hiển thị popup thông báo lỗi
                    Swal.fire({
                        icon: 'error',
                        title: 'Update Failed',
                        text: 'Form is not valid. Please check the errors.',
                    });
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }

    function deleteProduct(productId) {
        fetch('/delete_product/' + productId + '/', {
            method: 'DELETE',
            headers: {
                'X-CSRFToken': document.getElementsByName('csrfmiddlewaretoken')[0].value,
            },
        })
            .then(response => response.json())
            .then(data => {
                if (data.success) {
                
                    Swal.fire({
                        icon: 'success',
                        title: 'Delete Successful',
                        showConfirmButton: false,
                        timer: 1500,
                    });
                    location.reload();
                } else {

                    Swal.fire({
                        icon: 'error',
                        title: 'Delete Failed',
                        text: 'Something went wrong. Please try again.',
                    });
                    console.error('Delete failed');
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }
    function addProduct() {
    var form = document.getElementById('addProductForm');
    var formData = new FormData(form);
    fetch('/add_product/', {
        method: 'POST',
        body: formData,
        headers: {
            'X-CSRFToken': document.getElementsByName('csrfmiddlewaretoken')[0].value,
        },
    })
    .then(response => response.json())
    .then(data => {
        if (data.success) {
            Swal.fire({
                icon: 'success',
                title: 'Product Added Successfully',
                showConfirmButton: true,
                timer: 1500,
            });
            location.reload();
        } else {
            Swal.fire({
                icon: 'error',
                title: 'Add Product Failed',
                text: 'Something went wrong. Please try again.',
            });
            console.error('Add product failed');
        }
    })
    .catch(error => {
        console.error('Error:', error);
    });
}
</script>
{% endblock %}